In [1]:
import scanpy as sc
import pandas as pd
import pickle
import numpy as np
import graph_tool.all as gt
import anndata
%matplotlib inline
%pylab

/usr/lib/python3/dist-packages/graph_tool/draw/cairo_draw.py:39: RuntimeWarning: Error importing cairo. Graph drawing will not work.
  warnings.warn(msg, RuntimeWarning)
/usr/lib/python3/dist-packages/graph_tool/draw/cairo_draw.py:39: RuntimeWarning: Error importing cairo. Graph drawing will not work.
  warnings.warn(msg, RuntimeWarning)
/usr/lib/python3/dist-packages/graph_tool/draw/cairo_draw.py:39: RuntimeWarning: Error importing cairo. Graph drawing will not work.
  warnings.warn(msg, RuntimeWarning)
/usr/lib/python3/dist-packages/graph_tool/all.py:40: RuntimeWarning: Error importing draw module, proceeding nevertheless: /usr/lib/python3/dist-packages/cairo/_cairo.cpython-37m-x86_64-linux-gnu.so: undefined symbol: cairo_tee_surface_index
  warnings.warn(msg, RuntimeWarning)


Using matplotlib backend: TkAgg
Populating the interactive namespace from numpy and matplotlib


In [2]:
state4=pickle.load(open('adata_10x/10x_equilibrate_final_test/10x_state4.pkl','rb'))

In [4]:
state4

<NestedBlockState object, with base <BlockState object with 61 blocks (61 nonempty), for graph <Graph object, undirected, with 860 vertices and 5976 edges at 0x7fb75bb33610>, at 0x7fb70c6adf10>, and 5 levels of sizes [(860, 61), (61, 13), (13, 4), (4, 2), (2, 1)] at 0x7fb75bb33e50>

In [14]:
bs = state4.get_bs()                   
bs += [np.zeros(1)] * (10 - len(bs))
state = state4.copy(bs=bs, sampling=True)

state.mcmc_sweep(d=0.1,niter=1000)

(31.156620850214846, 946922, 280080)

In [18]:
state

<NestedBlockState object, with base <BlockState object with 62 blocks (61 nonempty), for graph <Graph object, undirected, with 860 vertices and 5976 edges at 0x7fb75bb33610>, at 0x7fb7080cca10>, and 10 levels of sizes [(860, 61), (61, 14), (14, 4), (4, 2), (2, 2), (2, 2), (2, 1), (1, 1), (1, 1), (1, 1)] at 0x7fb7080ccc10>

In [19]:
state.get_levels()[2]

<BlockState object with 7 blocks (4 nonempty), for graph <Graph object, undirected, with 16 vertices and 35 edges at 0x7fb7080ef310>, at 0x7fb703be1a10>

In [24]:
pv = None
for i in range(100):
    state.mcmc_sweep(d=0.1, niter=10)
    pv = state.get_levels()[2].collect_vertex_marginals(pv)

In [25]:
[x for x in pv]

[array([ 9,  0,  6, 14,  3, 28,  4, 12,  8, 16], dtype=int32),
 array([19,  7, 16,  6,  6, 11,  9,  1, 12,  1,  5,  7], dtype=int32),
 array([ 0, 51,  0,  0,  0,  0,  0, 29,  0, 15,  5], dtype=int32),
 array([17,  6,  4,  9,  5, 10,  7, 11, 12,  5,  4, 10], dtype=int32),
 array([ 0,  1,  6, 14, 18,  0,  7, 16,  4, 16, 18], dtype=int32),
 array([14,  0, 12, 20,  1, 17,  6,  5,  8, 16,  0,  1], dtype=int32),
 array([ 3, 11,  4,  6, 14,  8,  3, 34,  5,  8,  2,  2], dtype=int32),
 array([ 0, 53,  0,  0,  0,  0,  0, 30,  0, 12,  5], dtype=int32),
 array([ 8,  6,  6, 20,  4, 15,  4, 15,  2, 16,  2,  2], dtype=int32),
 array([12, 25, 10,  5,  6,  8,  3, 12,  8,  5,  3,  3], dtype=int32),
 array([12, 12,  6,  4, 12, 10,  6, 12,  8, 12,  5,  1], dtype=int32),
 array([ 7,  0,  7, 18,  4, 23,  1, 21,  7, 12], dtype=int32),
 array([ 6,  7, 10, 14,  8,  1,  9, 18,  9,  5, 10,  3], dtype=int32),
 array([13,  0, 11, 17,  8, 16,  4,  3,  9, 17,  0,  2], dtype=int32),
 array([15,  0, 13, 17,  3, 19,  5

In [27]:
pv = None
for i in range(10):
    state.mcmc_sweep(d=0.1, niter=1000)
    pv = state.get_levels()[2].collect_vertex_marginals(pv)
[x for x in pv]

[array([0, 0, 0, 6, 0, 1, 0, 0, 3], dtype=int32),
 array([0, 0, 1, 6, 0, 0, 0, 0, 3], dtype=int32),
 array([0, 1, 1, 2, 0, 0, 1, 0, 4, 0, 0, 1], dtype=int32),
 array([2, 0, 1, 5, 0, 0, 1, 0, 0, 0, 1], dtype=int32),
 array([2, 0, 0, 1, 0, 0, 1, 0, 0, 4, 0, 2], dtype=int32),
 array([3, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1], dtype=int32),
 array([0, 0, 0, 0, 2, 0, 1, 1, 0, 6], dtype=int32),
 array([0, 1, 0, 0, 2, 0, 1, 1, 1, 4], dtype=int32),
 array([4, 0, 0, 0, 1, 1, 4], dtype=int32),
 array([0, 1, 0, 0, 0, 1, 1, 0, 2, 4, 0, 1], dtype=int32),
 array([0, 0, 0, 0, 1, 1, 2, 2, 1, 0, 1, 2], dtype=int32),
 array([0, 0, 0, 6, 0, 0, 0, 1, 3], dtype=int32),
 array([0, 0, 0, 3, 0, 0, 3, 0, 2, 0, 1, 1], dtype=int32),
 array([0, 0, 0, 5, 0, 1, 0, 0, 4], dtype=int32),
 array([0, 1, 1, 3, 0, 0, 0, 2, 3], dtype=int32),
 array([2, 1, 0, 1, 0, 0, 3, 0, 1, 0, 1, 1], dtype=int32),
 array([1, 0, 0, 1, 2, 0, 3, 2, 0, 1], dtype=int32),
 array([3, 1, 2, 0, 0, 0, 0, 0, 1, 0, 2, 1], dtype=int32),
 array([2, 0, 0, 2,